### ISSUE TITLE
Record demo videos

### ISSUE THREAD

**Issue by pabreblob** [pabreblob/capsulefy#178]
- User sign up, showing legal text
-Improved dashboard
-Improved capsule display
-Password change
Estimated time: 2h
Deadline: 2/05

**Comment by pabreblob** [comment]
Record the creation of a new capsule, refreshing the deadman timer and deleting the user account

**Comment by adrcanfer** [comment]
Estimated 3h: 0,5h x 6 videos
Inverted: 3h
